import type { Metadata } from 'next';
import './globals.css';
import NavbarView from './common/components/views/NavbarView';

export const metadata: Metadata = {
  title: 'Submission App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavbarView />
        <main className="bg-purple-100">{children}</main>
      </body>
    </html>
  );
}
